name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install pytest
      - name: Run test calculate_expression
        run: |
          pytest test_calculate_expression.py
      - name: Run test get_pong
        run: |
          pytest test_get_pong.py
      - name: Run test get_random
        run: |
          pytest test_get_random.py
